### ISSUE TITLE
widget not displaying with fresh install

### ISSUE THREAD

**Issue by jgunstone** [manzt/quak#71]
![Image](https://github.com/user-attachments/assets/0c118f61-c94c-4f63-81b9-33353cb5562b)

just tried with the following pixi environment...

`pixi.toml`
```toml
[project]
authors = ["jgunstone <j.gunstone@maxfordham.com>"]
channels = ["conda-forge"]
name = "0327-quak"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
jlab = "jupyter lab"

[dependencies]
jupyterlab = ">=4.3.6,<5"
ipywidgets = ">=8.1.5,<9"
polars = ">=1.26.0,<2"

[pypi-dependencies]
quak = ">=0.2.2, <0.3"

```
